// Mocks generated by Mockito 5.4.2 from annotations
// in bus_navigation/test/application/RoutesBloc/routes_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bus_navigation/features/routes/data_provider/recent_route_data_provider.dart'
    as _i2;
import 'package:bus_navigation/features/routes/models/recent_route.dart' as _i5;
import 'package:bus_navigation/features/routes/repository/recent_route_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRecentRouteDataProvider_0 extends _i1.SmartFake
    implements _i2.RecentRouteDataProvider {
  _FakeRecentRouteDataProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RecentRouteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecentRouteRepository extends _i1.Mock
    implements _i3.RecentRouteRepository {
  MockRecentRouteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RecentRouteDataProvider get dataProvider => (super.noSuchMethod(
        Invocation.getter(#dataProvider),
        returnValue: _FakeRecentRouteDataProvider_0(
          this,
          Invocation.getter(#dataProvider),
        ),
      ) as _i2.RecentRouteDataProvider);
  @override
  _i4.Future<List<_i5.RecentRouteModel>> getAllRoutes() => (super.noSuchMethod(
        Invocation.method(
          #getAllRoutes,
          [],
        ),
        returnValue: _i4.Future<List<_i5.RecentRouteModel>>.value(
            <_i5.RecentRouteModel>[]),
      ) as _i4.Future<List<_i5.RecentRouteModel>>);
  @override
  _i4.Future<void> addRecentRoute(_i5.RecentRouteModel? recentRoute) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRecentRoute,
          [recentRoute],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
  @override
  List<_i5.RecentRouteModel> getUniqueRoutes(
          List<_i5.RecentRouteModel>? routes) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUniqueRoutes,
          [routes],
        ),
        returnValue: <_i5.RecentRouteModel>[],
      ) as List<_i5.RecentRouteModel>);
}
