// import 'package:bus_navigation/features/nav_detail/model/nav_detail_model.dart';

// NavDetailModel navDetailModel = NavDetailModel(
//   startTime: DateTime.utc(2023),
//   endTime: DateTime.now(),
//   duration: 120,
//   legs: [
//     Leg(
//       startTime: DateTime(2023, 02, 02, 4, 30, 7, 6),
//       endTime: DateTime.now(),
//       mode: 'BUS',
//       from: 'Piassa',
//       to: '4 Kilo',
//       duration: 234,
//       routeShortName: 'E-M',
//       routeLongName: 'Ayat ↔ Tor Hailoch',
//       agencyName: "Anbessa",
//     ),
//     Leg(
//       startTime: DateTime(2023, 02, 02, 4, 30, 7, 6),
//       endTime: DateTime.now(),
//       mode: 'WALK',
//       from: 'Piassa',
//       distance: 544.2,
//       to: '4 Kilo',
//       duration: 30,
//     ),
//     Leg(
//       startTime: DateTime(2023, 02, 02, 4, 30, 7, 6),
//       endTime: DateTime.now(),
//       mode: 'TRAIN',
//       from: 'Piassa',
//       to: '4 Kilo',
//       duration: 30,
//       routeShortName: 'A2S',
//       routeLongName: 'Ayat ↔ Tor Hailoch',
//       agencyName: "Ethiopia train coorp",
//     ),
//     Leg(
//       startTime: DateTime(2023, 02, 02, 4, 30, 7, 6),
//       endTime: DateTime.now(),
//       mode: 'WALK',
//       from: 'Piassa',
//       distance: 544.2,
//       to: '4 Kilo',
//       duration: 30,
//     ),
//     Leg(
//       startTime: DateTime(2023, 02, 02, 4, 30, 7, 6),
//       endTime: DateTime.now(),
//       mode: 'TRAIN',
//       from: 'Piassa',
//       to: '4 Kilo',
//       duration: 30,
//       routeShortName: 'A2S',
//       agencyName: "Ethiopia train coorp",
//       routeLongName: 'Ayat ↔ Tor Hailoch',
//     ),
//     Leg(
//       startTime: DateTime(2023, 02, 02, 4, 30, 7, 6),
//       endTime: DateTime.now(),
//       mode: 'BUS',
//       from: 'Piassa',
//       to: '4 Kilo',
//       duration: 234,
//       routeShortName: 'E-M',
//       agencyName: "Sheger",
//       routeLongName: 'Ayat ↔ Tor Hailoch',
//     ),
//   ],
// );
